In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("downloads/dictionary.csv")

In [3]:
print(df)

                            word  \
0      abandoned industrial site
1              abandoned vehicle
2                 abiotic factor
3                    access road
4              access to the sea
...                          ...
49532                     casing
49533                     facing
49534                     lining
49535         assumption of Mary
49536               auscultation

                                              definition
0      Site that cannot be used for any purpose, bein...
1      A vehicle that has been discarded in the envir...
2      Physical, chemical and other non-living enviro...
3      Any street or narrow stretch of paved surface ...
4      The ability to bring goods to and from a port ...
...                                                  ...
49532  Something put around something else, usually i...
49533  Something put around something else, usually i...
49534  Something put around something else, usually i...
49535  Catholic holiday on August 15, remembering the...
49536  Listening to the heart and lungs using a steth...

[49537 rows x 2 columns]

In [4]:
df.columns

Index(['word', 'definition'], dtype='str')

In [5]:
df[['word', 'definition']]

,word,definition
0,abandoned industrial site,"Site that cannot be used for any purpose, bein..."
1,abandoned vehicle,A vehicle that has been discarded in the envir...
2,abiotic factor,"Physical, chemical and other non-living enviro..."
3,access road,Any street or narrow stretch of paved surface ...
4,access to the sea,The ability to bring goods to and from a port ...
...,...,...
49532,casing,"Something put around something else, usually i..."
49533,facing,"Something put around something else, usually i..."
49534,lining,"Something put around something else, usually i..."
49535,assumption of Mary,"Catholic holiday on August 15, remembering the..."
49536,auscultation,Listening to the heart and lungs using a steth...

In [6]:
df.loc[df['word'] == 'lining']['definition']

49534    Something put around something else, usually i...
Name: definition, dtype: str

In [11]:
import os
os.chdir('..')
print(os.getcwd())

C:\Users\perei\Documents\MyLearn\2026-07_Udemy_PythonMegaCourse_ArditSulce\App4_Your_Weather_API

In [12]:
pd.read_csv("downloads/data_small/stations.txt", skiprows=17)

,STAID,STANAME,CN,LAT,LON,HGHT
0,1,VAEXJOE,SE,+56:52:00,+014:48:00,166
1,2,FALUN,SE,+60:37:00,+015:37:00,160
2,3,STENSELE,SE,+65:04:00,+017:09:59,325
3,4,LINKOEPING,SE,+58:24:00,+015:31:59,93
4,5,LINKOEPING-MALMSLAETT,SE,+58:24:00,+015:31:59,93
...,...,...,...,...,...,...
6449,25149,LEBORK,PL,+54:33:11,+017:43:24,44
6450,25150,GDANSK-REBIECHOWO_OLD,PL,+54:22:59,+018:28:00,144
6451,25151,ELBLAG-MILEJEWO,PL,+54:13:23,+019:32:36,151
6452,25156,KROSNO,PL,+49:42:24,+021:46:09,326
6453,25157,YLJA KRAFTVERK,NO,+61:11:49,+008:22:50,517